name: Hello CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.413"
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet test --no-build

  deploy-qa:
    name: Deploy to QA
    if: github.event.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: qa
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Package & Deploy
        run: |
          chmod +x ./build.sh
          ./build.sh
          npm i -g serverless
          sls deploy -s qa -r ap-southeast-2
