name: Hello CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: dotnet build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.413"
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet test --no-build
